export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOG_IN_FAILED = 'USER_LOG_IN_FAILED';
export const LOGIN_USER = 'LOGIN_USER';
export const EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE';
export const EMPLOYEE_CREATE = 'EMPLOYEE_CREATE';
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';